--1
Select * from Customer


--2. Get all customer Orders, CustomerId, OrderId
SELECT [Name],[Email],[Status],[OrderDate],[CustomerId],[OrderId]
FROM Customer, Orders
WHERE Customer.Id = Orders.CustomerId;

--3. Get total revenue generated by Customer Name ="SAM"
SELECT C.Name,SUM(P.Cost) AS Total_Revenue FROM
Customer C JOIN Orders O ON C.Id = O.CustomerId JOIN Product P ON O.ProductId = P.CategoryId
GROUP BY c.Name
HAVING C.Name = 'HUGO';

--4 Get Order Details for Cost>900
SELECT O.OrderId, O.Status, O.OrderDate, O.ProductId, O.CustomerId, P.Cost
FROM Orders O JOIN Product P ON P.CateogoryId = O.ProductId
WHERE P.Cost>900;
--5. Get Order Details for Dates between Oct 1, 2022 and Oct 30, 20
SELECT [OrderId], [Status],[OrderDate],[ProductId],[CustomerId]
FROM Orders WHERE Orders.OrderDate BETWEEN '2022/10/01' AND '2022-10-30';
--6 Get Customer Name, Product Name Purchased, Product Cost for all customers
SELECT C.Name AS "Customer Name", P.Name AS "Product_Name", P.Cost
FROM Customer C JOIN Orders O
ON C.Id = O.CustomerId
JOIN Product P ON O.ProductId = P.CateogoryId
ORDER BY C.Name;
--7 Get All Customers that contain third letter as "t" and last letter as "s"
SELECT * FROM Customer
WHERE SUBSTRING(Customer.Name,3,1) = 't' AND Customer.Name LIKE '%s';
SELECT * FROM Customer;
SELECT * FROM Orders;
SELECT * FROM Product;
SELECT * FROM ProductCategory;

-------------------------------------

Use EShop

--Get the top 2 most expensive orders
select top 2 * from Orders, Product
where Orders.ProductId=Product.ID
order by Product.Cost desc

--Get all order Details grouped by status

select count(*),[Status] from Orders
group by [Status]

--Group all products (total products count) by category
select count(*) ,ProductCategory.[Name] from Product,ProductCategory
where Product.CateogoryId=ProductCategory.ID
group by ProductCategory.[Name]

