USE EShop

--THis is a comment
--Get all products
Select *from Product

--Get all products that have categoryid=10
Select *from Product
Where CateogoryId=10 

--Get total cost of products listed with categoryid=10
Select Sum(Cost) from Product
Where CateogoryId=10

--Get Product name,cost from Product table
Select Name,Cost from Product

--Save above as view

CREATE VIEW vw_Product AS
(Select Name, Cost from Product)

--See the view result
select* from vw_Product

--Get all products that start with 'K'

Select * from Product
Where Name Like'K%'

--Get all products that start have the second character as 'e'
Select * from Product
Where Name Like'_e%'

--Get all products whose cost is not equal to 5000
Select * from Product
Where Cost <> 5000

--'^%s$' =>The word starts (^) with any charcter and consists 's' at the end ($)
Select * from Product
Where Name LIKE '%s'
--Select all products with names as 'T-Shirt','Iphone','Kurti'

Select * from Product
Where Name='T-Shirt' OR Name='Iphone 14' OR Name='Kurti'

--Better technique
Select * from Product
Where Name in ('T-Shirt','Iphone 14','Kurti')

--Get all products having a category id matching a category in ProductCategory table
Select * from Product
Where CateogoryId IN (Select Id from ProductCategory)

--Get the order for customer name
--Customer Table has Customer Name
--Order Id is in Orders table

Select[Name],[OrderID] from Customer,Orders
WHERE Customer.ID=Orders.CustomerId

--Get total revenue generated by sai
--Customer Name from Customer table
--Total cost from Product
--Orders table contains Customer purchases

Select SUM(Cost)
From Orders, Customer, Product
WHERE Orders.CustomerId=Customer.Id
AND Orders.ProductId=Product.Id
AND Customer.Name='Eena'